"""
MIDI export for the research pipeline's generated chord sequences.

Renders a chord_progression + chord_duration pair (as produced by
NthOrderMarkovChain.generate) into a block-chord music21 stream and
writes it to a .mid file, so generated sequences can be played back
with the existing MidiPlayer / MIDI Player GUI.

Rhythm is intentionally not merged in: it is generated by an
independent Markov chain with no shared timeline with the chord
chain, so combining them would be an arbitrary alignment rather than
a real reconstruction.
"""

from pathlib import Path

from music21 import harmony, stream, tempo


def chords_to_midi_stream(
    chord_progression: list[str], chord_duration: list[float]
) -> stream.Stream:
    """Render a chord-progression/chord-duration pair as a block-chord stream."""
    s = stream.Stream()
    s.append(tempo.MetronomeMark(number=100))

    for label, duration in zip(chord_progression, chord_duration):
        if duration <= 0:
            continue
        try:
            cs = harmony.ChordSymbol(label)
        except Exception:
            continue
        cs.duration.quarterLength = duration
        s.append(cs)

    return s


def save_chords_as_midi(
    chord_progression: list[str], chord_duration: list[float], path: str
) -> None:
    """Render a chord sequence and write it to `path` as a MIDI file."""
    s = chords_to_midi_stream(chord_progression, chord_duration)
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    s.write("midi", path)
